---
- name: bootstrapping and new user
  hosts: raiders
  gather_facts: False

  tasks:
  - name: remove a user
    user:
      name: exampleuser
      state: absent
      remove: yes
    become: yes

  - name: remove the group sandbox
    group:
      name: sandbox
      state: absent
    become: yes
