---
- name: Wednesday Challenge
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - vars/wed_chall.yml


  tasks:
    - name: Create output file to be placed on hosts home directory
      template:
        src: templates/wed.j2    # name of the template on ansible controller
        dest: /home/{{ ansible_user }}/wed_challenge.txt              # name of the completed file to be placed on the target system

